# Toggles whether the main cookie is automatically clicked.
mainAutoClickerEnabled = true

# Toggles whether golden cookies are automatically clicked.
goldenCookieClickerEnabled = true

# Toggles management of the stock market minigame.
stockMarketEnabled = true

# Toggles management of the garden minigame.
gardenEnabled = true

# Used with the stock minigame. The threshold at which the bot will buy a specific stock. Recommended to be
# -120.0 < x < -80.0 in order to turn a tidy profit.
buyLimit = -100.0

# Used with the stock minigame. The threshold at which the bot will sell a specific stock. Recommended to be
# 80.0 < x < 120.0 in order to turn a tidy profit in a reasonable amount of time.
sellLimit = 90.0
