saveLocation = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Cookie Clicker\\resources\\app\\save\\save.cki"
# Toggles whether the main cookie is automatically clicked.
mainAutoClickerEnabled = true

# Toggles whether golden cookies are automatically clicked.
goldenCookieClickerEnabled = true

# Toggles management of the stock market minigame.
stockMarketEnabled = true

# Toggles management of the garden minigame.
gardenEnabled = false

# Used with the stock minigame. The threshold at which the bot will buy a specific stock.
buyLimit = -90.0

# Used with the stock minigame. The threshold at which the bot will sell a specific stock.
sellLimit = 50.0
